[package]
name = "windows-shortcuts"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotters = "0.3.4"
native-windows-gui = "1.0.13"
native-windows-derive = "1.0.5"

[build-dependencies]
embed-resource = "1.3"