[package]
name = "windows-shortcuts"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotters = "0.3.4"
native-windows-gui = "1.0.13"
native-windows-derive = "1.0.5"
winreg = "0.11.0"

[dependencies.windows]
version = "0.44.0"
features = [
    "Win32_Devices_Display",
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_System_Threading",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_DataExchange",
]

[build-dependencies]
embed-resource = "1.3"
