mod adb;
mod app;
mod config;
pub mod constants;
mod explorer;
mod inputs;
pub mod macros;
mod magic_packet;
mod monitors;
mod night_light;
mod registry;
mod server;
mod startup;
mod trayicon;
pub mod utils;
pub use crate::app::start_app;
pub use crate::config::Config;
